networks:
  spoilnomore:
    driver: bridge

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: shelfdb
    volumes:
      - shelfdb-data:/var/lib/postgresql/data
    ports:
      - "5947:5432"
    networks:
      - spoilnomore

  redis:
    image: redis:latest
    container_name: redisserver
    ports:
      - "6379:6379"  # Default Redis port
    networks:
      - spoilnomore

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: flaskserver
    depends_on:
      - db
      - redis
    ports:
      - "8081:8081"
    networks:
      - spoilnomore
    environment:
      - CELERY_BROKER_URL=redis://redisserver:6379/0
      - result_backend=redis://redisserver:6379/0

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celeryworker
    command: celery -A app.celery worker --loglevel=debug
    depends_on:
      - backend
      - redis
    env_file: 
      - .env  # Include the .env file here
    networks:
      - spoilnomore

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celerybeat
    command: celery -A app.celery beat --loglevel=debug
    depends_on:
      - backend
      - redis
    env_file: 
      - .env  # Include the .env file here
    volumes:
      - celerybeat-data:/app/celerybeat-data
    networks:
      - spoilnomore



  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shelflife
    depends_on:
      - backend
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    networks:
      - spoilnomore

volumes:
  shelfdb-data:
  celerybeat-data:
