version: '3.8'

networks:
  spoilnomore:
    driver: bridge

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: shelfdb
    volumes:
      - shelfdb-data:/var/lib/postgresql/data
    ports:
      - "5947:5432"
    networks:
      - spoilnomore

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flaskserver
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - spoilnomore

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shelflife
    depends_on:
      - backend
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    networks:
      - spoilnomore

volumes:
  shelfdb-data:
