name: Vue.js CI

on:
  # Triggers the workflow on push or pull request to the default branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your node version here

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Optionally, you can run linting as well
      #- name: Run linting
      #  run: npm run lint
